import os

# YesCaptcha API ayarları
YESCAPTCHA_API_KEY = os.getenv('YESCAPTCHA_API_KEY', '3850773cda8581361a553b1f3712102c1dd44de179197')
YESCAPTCHA_API_URL = "https://api.yescaptcha.com"

# Alternatif olarak China node kullanılabilir
# YESCAPTCHA_API_URL = "https://cn.yescaptcha.com"

# Captcha çözme ayarları
CAPTCHA_TIMEOUT = 60  # saniye
CAPTCHA_MAX_ATTEMPTS = 3

# Desteklenen captcha soruları (İngilizce)
SUPPORTED_QUESTIONS = [
    "Pick the ant",
    "Pick the apple", 
    "Pick the banana",
    "Pick the bat",
    "Pick the bear",
    "Pick the bee",
    "Pick the bread",
    "Pick the butterfly",
    "Pick the camel",
    "Pick the cat",
    "Pick the chicken",
    "Pick the cow",
    "Pick the crab",
    "Pick the deer",
    "Pick the dinosaur",
    "Pick the dog",
    "Pick the dolphin",
    "Pick the donut",
    "Pick the duck",
    "Pick the elephant",
    "Pick the frog",
    "Pick the giraffe",
    "Pick the goat",
    "Pick the grapes",
    "Pick the icecream",
    "Pick the ice cream",
    "Pick the kangaroo",
    "Pick the koala",
    "Pick the ladybug",
    "Pick the lion",
    "Pick the lobster",
    "Pick the monkey",
    "Pick the mouse",
    "Pick the octopus",
    "Pick the owl",
    "Pick the parrot",
    "Pick the panda",
    "Pick the pig",
    "Pick the pineapple",
    "Pick the pizza",
    "Pick the rabbit",
    "Pick the rhino",
    "Pick the seal",
    "Pick the shark",
    "Pick the sheep",
    "Pick the snail",
    "Pick the snake",
    "Pick the starfish",
    "Pick the turtle",
    "Pick the zebra"
]

# Türkçe-İngilizce çeviri sözlüğü
TURKISH_TO_ENGLISH = {
    "aslan": "lion",
    "kedi": "cat", 
    "köpek": "dog",
    "kuş": "bird",
    "balık": "fish",
    "araba": "car",
    "ev": "house",
    "ağaç": "tree",
    "çiçek": "flower",
    "elma": "apple",
    "muz": "banana",
    "seç": "pick",
    "bul": "find",
    "göster": "show",
    "tavuk": "chicken",
    "inek": "cow",
    "maymun": "monkey",
    "fare": "mouse",
    "kaplan": "tiger",
    "ayı": "bear",
    "kurt": "wolf",
    "tilki": "fox",
    "zebra": "zebra",
    "fil": "elephant",
    "gergedan": "rhino",
    "zürafa": "giraffe",
    "kanguru": "kangaroo",
    "koala": "koala",
    "panda": "panda",
    "penguen": "penguin",
    "balina": "whale",
    "yunus": "dolphin",
    "köpekbalığı": "shark",
    "fok": "seal",
    "denizanası": "jellyfish",
    "yıldız balığı": "starfish",
    "ahtapot": "octopus",
    "yengeç": "crab",
    "ıstakoz": "lobster",
    "kelebek": "butterfly",
    "arı": "bee",
    "uğur böceği": "ladybug",
    "karınca": "ant",
    "örümcek": "spider",
    "salyangoz": "snail",
    "kurbağa": "frog",
    "yılan": "snake",
    "kaplumbağa": "turtle",
    "timsah": "crocodile",
    "kartal": "eagle",
    "baykuş": "owl",
    "papağan": "parrot",
    "ördek": "duck",
    "kaz": "goose",
    "horoz": "rooster",
    "tavşan": "rabbit",
    "sincap": "squirrel",
    "kirpi": "hedgehog",
    "gelincik": "ferret",
    "sıçan": "rat",
    "hamster": "hamster",
    "guinea pig": "guinea pig",
    "at": "horse",
    "eşek": "donkey",
    "katır": "mule",
    "deve": "camel",
    "gergedan": "rhino",
    "su aygırı": "hippo",
    "gergedan": "rhino",
    "zürafa": "giraffe",
    "kanguru": "kangaroo",
    "koala": "koala",
    "panda": "panda",
    "penguen": "penguin",
    "balina": "whale",
    "yunus": "dolphin",
    "köpekbalığı": "shark",
    "fok": "seal",
    "denizanası": "jellyfish",
    "yıldız balığı": "starfish",
    "ahtapot": "octopus",
    "yengeç": "crab",
    "ıstakoz": "lobster",
    "kelebek": "butterfly",
    "arı": "bee",
    "uğur böceği": "ladybug",
    "karınca": "ant",
    "örümcek": "spider",
    "salyangoz": "snail",
    "kurbağa": "frog",
    "yılan": "snake",
    "kaplumbağa": "turtle",
    "timsah": "crocodile",
    "kartal": "eagle",
    "baykuş": "owl",
    "papağan": "parrot",
    "ördek": "duck",
    "kaz": "goose",
    "horoz": "rooster",
    "tavşan": "rabbit",
    "sincap": "squirrel",
    "kirpi": "hedgehog",
    "gelincik": "ferret",
    "sıçan": "rat",
    "hamster": "hamster",
    "guinea pig": "guinea pig",
    "at": "horse",
    "eşek": "donkey",
    "katır": "mule",
    "deve": "camel"
}
